/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as AuctionsUuidRouteImport } from './routes/auctions_/$uuid'
import { Route as AuctionsUuidBetsRouteImport } from './routes/auctions_/$uuid/bets'
import { Route as AuctionsUuidBetsNewRouteImport } from './routes/auctions_/$uuid/bets.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsUuidRoute = AuctionsUuidRouteImport.update({
  id: '/auctions_/$uuid',
  path: '/auctions/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsUuidBetsRoute = AuctionsUuidBetsRouteImport.update({
  id: '/bets',
  path: '/bets',
  getParentRoute: () => AuctionsUuidRoute,
} as any)
const AuctionsUuidBetsNewRoute = AuctionsUuidBetsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuctionsUuidBetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/auctions/$uuid': typeof AuctionsUuidRouteWithChildren
  '/auctions/$uuid/bets': typeof AuctionsUuidBetsRouteWithChildren
  '/auctions/$uuid/bets/new': typeof AuctionsUuidBetsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/auctions/$uuid': typeof AuctionsUuidRouteWithChildren
  '/auctions/$uuid/bets': typeof AuctionsUuidBetsRouteWithChildren
  '/auctions/$uuid/bets/new': typeof AuctionsUuidBetsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/auctions_/$uuid': typeof AuctionsUuidRouteWithChildren
  '/auctions_/$uuid/bets': typeof AuctionsUuidBetsRouteWithChildren
  '/auctions_/$uuid/bets/new': typeof AuctionsUuidBetsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auctions'
    | '/auctions/$uuid'
    | '/auctions/$uuid/bets'
    | '/auctions/$uuid/bets/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auctions'
    | '/auctions/$uuid'
    | '/auctions/$uuid/bets'
    | '/auctions/$uuid/bets/new'
  id:
    | '__root__'
    | '/'
    | '/auctions'
    | '/auctions_/$uuid'
    | '/auctions_/$uuid/bets'
    | '/auctions_/$uuid/bets/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuctionsRoute: typeof AuctionsRoute
  AuctionsUuidRoute: typeof AuctionsUuidRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions_/$uuid': {
      id: '/auctions_/$uuid'
      path: '/auctions/$uuid'
      fullPath: '/auctions/$uuid'
      preLoaderRoute: typeof AuctionsUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions_/$uuid/bets': {
      id: '/auctions_/$uuid/bets'
      path: '/bets'
      fullPath: '/auctions/$uuid/bets'
      preLoaderRoute: typeof AuctionsUuidBetsRouteImport
      parentRoute: typeof AuctionsUuidRoute
    }
    '/auctions_/$uuid/bets/new': {
      id: '/auctions_/$uuid/bets/new'
      path: '/new'
      fullPath: '/auctions/$uuid/bets/new'
      preLoaderRoute: typeof AuctionsUuidBetsNewRouteImport
      parentRoute: typeof AuctionsUuidBetsRoute
    }
  }
}

interface AuctionsUuidBetsRouteChildren {
  AuctionsUuidBetsNewRoute: typeof AuctionsUuidBetsNewRoute
}

const AuctionsUuidBetsRouteChildren: AuctionsUuidBetsRouteChildren = {
  AuctionsUuidBetsNewRoute: AuctionsUuidBetsNewRoute,
}

const AuctionsUuidBetsRouteWithChildren =
  AuctionsUuidBetsRoute._addFileChildren(AuctionsUuidBetsRouteChildren)

interface AuctionsUuidRouteChildren {
  AuctionsUuidBetsRoute: typeof AuctionsUuidBetsRouteWithChildren
}

const AuctionsUuidRouteChildren: AuctionsUuidRouteChildren = {
  AuctionsUuidBetsRoute: AuctionsUuidBetsRouteWithChildren,
}

const AuctionsUuidRouteWithChildren = AuctionsUuidRoute._addFileChildren(
  AuctionsUuidRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuctionsRoute: AuctionsRoute,
  AuctionsUuidRoute: AuctionsUuidRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
